CREATE TABLE IF NOT EXISTS `contragents` (
  `id` int(15) NOT NULL AUTO_INCREMENT,
  `relativity` int(10) NOT NULL,
  `name` varchar(100) NOT NULL,
  `address` text NOT NULL,
  `fullinfo` text NOT NULL,
  `contacts` text NOT NULL,
  `contragent_amount` decimal(20,2) NOT NULL,
  `contragent_dolg` decimal(20,2) NOT NULL,
  `contragent_completed` decimal(20,2) NOT NULL,
  `contragent_from_money_table` decimal(10,2) NOT NULL,
  `contragent_inwork` decimal(20,2) NOT NULL,
  `notification_number` varchar(30) NOT NULL,
  `qr_success` int(10) NOT NULL,
  `gpt_note` text,
  `gpt_keywords` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `contragent_dolg` (`contragent_dolg`),
  KEY `idx_contragents_name` (`name`),
  KEY `idx_contragents_amount` (`contragent_amount`),
  KEY `gpt_c_idx_name` (`name`),
  KEY `gpt_c_idx_amount` (`contragent_amount`),
  KEY `gpt_c_idx_dolg` (`contragent_dolg`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
